INSERT INTO COURSE VALUES(1, 'Math');
INSERT INTO COURSE VALUES(2, 'English');

INSERT INTO STUDENT VALUES(1, 'John');
INSERT INTO STUDENT VALUES(2, 'Cathy');

INSERT INTO STUDENT_COURSE VALUES(1,1);

INSERT INTO STUDENT_COURSE VALUES(1,2);

INSERT INTO STUDENT_COURSE VALUES(2,2);